### ISSUE TITLE
"python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lyc8tzkz/fastdtw/

### ISSUE THREAD

**Issue by CharulataShelar** [slaypni/fastdtw#26]
Hi All,

I have a RHEL 7 server and I have installed python 3.6 in virtual environment and I am trying to install fastdtw package in it but getting below error. I am not able to understand it, could you please help me resolve this issue.

------------------------------------------------------------------------------

(py36-venv) [user@server py36-venv]$ pip install fastdtw --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org
Collecting fastdtw
  Downloading https://files.pythonhosted.org/packages/fa/ef/a4cf2d72518b5fccd302 100% |ââââââââââââââââââââââââââââââââ| 122kB 2.7MB/s
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pytest-runner/: [SSL: CERTIFICATE_ERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lyc8tzkz/fastdtw/setup.py", line 77, in <module>
        setup(**kwargs)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lyc8tzkz/fastdtw/

**Comment by CharulataShelar** [comment]
I directly downloaded the package files and used it. 
Thanks
